### ISSUE TITLE
Integrate Ransomwhere dataset

### ISSUE THREAD

**Issue by CarlosLannister** [graphsense/graphsense-tagpacks#14]
It could be interesting to add https://ransomwhe.re/index.html#download, as new tag packs.

**Comment by behas** [comment]
True. Unfortunately the service is down. I leave it open for the moment.

**Comment by CarlosLannister** [comment]
Hi, 

I believed that in July you can download the data. But now the API is down and the data is made freely available to interested individuals and organizations.  Either way, I will try to contact the author, ransomwhere@lightningsecurity.io, and try to obtain the dataset.

**Comment by behas** [comment]
I'll close this issue for the moment. We can re-open when the dataset becomes available.

**Comment by CarlosLannister** [comment]
Hi, 

I managed to obtain the dataset, I can send it to you if you want. But now it is publicly available at https://ransomwhe.re/#download

**Comment by mdragaschnig** [comment]
Hi,

thanks for the offer! In the meantime we obtained the dataset ourselves  via https://api.ransomwhe.re/export
and added it 
https://github.com/graphsense/graphsense-tagpacks/commit/369a3279c7666d1eb4fc115a9e5a22697753a1d8

I just forgot to reopen this issue after doing so.
