### ISSUE TITLE
Documenting source instance for attribution rating and reference

### ISSUE THREAD

**Issue by VinceICPO** [graphsense/graphsense-tagpacks#2]
It will be useful to be able to contact the institution/individual who documented the tag. 
So, in addition to the name of the contributor, should we have a UID of the GraphSense instance this came from so we may contact the institution accountable for maintaining this instance?

**Comment by MatteoRomiti** [comment]
I'm not sure I understood. At the moment, we have the `source` field in each tagpack which points to the website where the tag is hosted. But I think you want to say it should be possible to contact the `creator` of the tagpack, right? In this case, the only information we have about the creator (through a pull request) is its GitHub, so it might make sense to have a bit more info about it, I agree.

**Comment by behas** [comment]
Each tagpack carries a git URI and uses that URI as part of a fully qualified tag URI.
