### ISSUE TITLE
Wrong currency in Satoshi Dice BCH tag pack?

### ISSUE THREAD

**Issue by wincentbalin** [graphsense/graphsense-tagpacks#33]
The [Satoshi Dice BCH tag pack](https://github.com/graphsense/graphsense-tagpacks/blob/master/packs/satoshidice_bch.yaml) has `currency: LTC` entry, but `BCH` in the name. Which of the two currencies is the correct one?

**Comment by mdragaschnig** [comment]
Thanks for reporting! 
BCH is the correct one; fixed in https://github.com/graphsense/graphsense-tagpacks/commit/8cda283a61b9820647f04b0da7b711b8a7467acd
