### ISSUE TITLE
Create VASP Actorpack

### ISSUE THREAD

**Issue by soad003** [graphsense/graphsense-tagpacks#35]
At least add vasp listed on https://www.walletexplorer.com/

and link to tags.

**Comment by soad003** [comment]
**Prerequisits**
- Tagpack-tool add actor mapping column to tag table
- (semi) automatic actor assignment (ask user if lable could match actor)

**Todos**

- [ ] link new actors in all other tagpacks

**Comment by mdragaschnig** [comment]
related to https://github.com/graphsense/graphsense-tagpack-tool/issues/41

**Comment by mdragaschnig** [comment]
mining actors have also been created, and miner tagpacks have been enriched using the proposed interactive workflow.
